<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Novolis.Geopolitics.Unit</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NovolisStackAnalyzers>false</NovolisStackAnalyzers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\..\apps\GeoPolity\GeoPolity.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Geopolitics.Core\Novolis.Geopolitics.Core.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Geopolitics.Simulation\Novolis.Geopolitics.Simulation.csproj" />
  </ItemGroup>
</Project>
